import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportData {
    caseId?: string;
    timestamp: string;
    matchType: string;
    score: string;
    targetFile: {
        name: string;
        size: number;
        type: string;
    };
    analysis: {
        sha256: string;
        pHash: string;
        embedding: string;
    };
    bestMatch?: {
        caseId: string;
        timestamp: string;
        userId: string;
        score: string;
        matchType: string;
    };
}

export const generateEvidenceReport = (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // --- Header ---
    doc.setFillColor(10, 15, 24); // Dark Blue/Black
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("AUTHENEX PROTECT", 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text("DIGITAL RIGHTS MANAGEMENT & FORENSIC REPORT", 14, 28);

    doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - 14, 20, { align: 'right' });
    doc.text(`Report ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, pageWidth - 14, 28, { align: 'right' });

    let yPos = 50;

    // --- Verdict Section ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("VERDICT ANALYSIS", 14, yPos);

    yPos += 10;

    const isMatch = data.matchType !== 'No Match';
    const color = isMatch ? [220, 38, 38] : [22, 163, 74]; // Red if match (suspicious/infringement found), Green if clean (original)
    // Actually, if verifying suspicious, a match means it IS a copy (which might be good or bad depending on intent).
    // Let's assume user is checking if "suspicious" content matches a "protected" original. 
    // If match found -> It IS the protected content.

    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(14, yPos, pageWidth - 28, 12, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text(`RESULT: ${data.matchType.toUpperCase()} (Confidence: ${data.score}%)`, pageWidth / 2, yPos + 8, { align: 'center' });

    yPos += 20;

    // --- Target File Details ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text("Target File Properties", 14, yPos);
    yPos += 6;

    autoTable(doc, {
        startY: yPos,
        head: [['Property', 'Value']],
        body: [
            ['File Name', data.targetFile.name],
            ['File Size', `${(data.targetFile.size / 1024).toFixed(2)} KB`],
            ['MIME Type', data.targetFile.type],
            ['SHA-256 Hash', data.analysis.sha256.substring(0, 32) + "..."],
            ['Perceptual Hash', data.analysis.pHash],
        ],
        theme: 'grid',
        headStyles: { fillColor: [40, 40, 40] }
    });

    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 15;

    // --- Match Details ---
    if (data.bestMatch) {
        doc.setFontSize(12);
        doc.text("Matched Source (Protected Original)", 14, yPos);
        yPos += 6;

        autoTable(doc, {
            startY: yPos,
            head: [['Property', 'Value']],
            body: [
                ['Source Case ID', data.bestMatch.caseId],
                ['Registration Date', new Date(data.bestMatch.timestamp).toLocaleString()],
                ['Owner ID', data.bestMatch.userId],
                ['Match Score', `${data.bestMatch.score}%`],
                ['Match Type', data.matchType]
            ],
            theme: 'grid',
            headStyles: { fillColor: [220, 50, 50] }
        });
    } else {
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("No matching protected content was found in the registry.", 14, yPos);
    }

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is generated by Authenex Protect. Authenticity can be verified via the Case ID.", 14, pageHeight - 10);

    doc.save(`Authenex_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
